/*
 * Decompiled with CFR 0.152.
 */
package net.ibizsys.model.pub.ionic;

import java.util.HashMap;
import net.ibizsys.model.pub.ionic.PSIonicViewCodePublisherImpl;

public class PSIonicIndexViewViewCodePublisherImpl
extends PSIonicViewCodePublisherImpl {
    public PSIonicIndexViewViewCodePublisherImpl() {
        throw new Error("Unresolved compilation problems: \n\tThe import SA cannot be resolved\n\tThe import SA cannot be resolved\n\tThe import SA cannot be resolved\n\tThe import SA cannot be resolved\n\tThe import SA cannot be resolved\n\tThe import SA cannot be resolved\n\tThe import SA cannot be resolved\n\tThe import SA cannot be resolved\n\tThe hierarchy of the type PSIonicIndexViewViewCodePublisherImpl is inconsistent\n\tiPSAppView cannot be resolved or is not a field\n\tIPSAppIndexView cannot be resolved to a type\n\tIPSAppIndexView cannot be resolved to a type\n\tIPSAppIndexView cannot be resolved to a type\n\tiPSAppView cannot be resolved or is not a field\n\tIPSAppMenu cannot be resolved to a type\n\tIPSAppMenuItem cannot be resolved to a type\n\tIPSAppMenuItem cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tPSPublishContextImpl cannot be resolved to a type\n\tPSPublishContextImpl cannot be resolved to a type\n\tThe method getDAGlobalHelper() is undefined for the type PSIonicIndexViewViewCodePublisherImpl\n\tIPSPFViewTempl cannot be resolved to a type\n\tiPSPFStyle cannot be resolved\n\tIPSPFViewTempl cannot be resolved to a type\n\tStringHelper cannot be resolved\n\tThe method getPSPFPubCode() is undefined for the type PSIonicIndexViewViewCodePublisherImpl\n\tIPSPFViewCodePublisher cannot be resolved to a type\n\tpsSubCodeMethod cannot be resolved to a variable\n\tpsSubCodeMethod cannot be resolved\n\tStringHelper cannot be resolved\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tiPSAppView cannot be resolved or is not a field\n\tiPSAppView cannot be resolved or is not a field\n\tiPSAppView cannot be resolved to a variable\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n");
    }

    @Override
    protected void onFillGenerateCodeParams(HashMap<String, Object> hashMap) throws Exception {
        throw new Error("Unresolved compilation problems: \n\tiPSAppView cannot be resolved or is not a field\n\tIPSAppIndexView cannot be resolved to a type\n\tIPSAppIndexView cannot be resolved to a type\n\tIPSAppIndexView cannot be resolved to a type\n\tiPSAppView cannot be resolved or is not a field\n\tIPSAppMenu cannot be resolved to a type\n\tIPSAppMenuItem cannot be resolved to a type\n\tIPSAppMenuItem cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tPSPublishContextImpl cannot be resolved to a type\n\tPSPublishContextImpl cannot be resolved to a type\n\tThe method getDAGlobalHelper() is undefined for the type PSIonicIndexViewViewCodePublisherImpl\n\tIPSPFViewTempl cannot be resolved to a type\n\tiPSPFStyle cannot be resolved\n\tIPSPFViewTempl cannot be resolved to a type\n\tStringHelper cannot be resolved\n\tThe method getPSPFPubCode() is undefined for the type PSIonicIndexViewViewCodePublisherImpl\n\tIPSPFViewCodePublisher cannot be resolved to a type\n\tpsSubCodeMethod cannot be resolved to a variable\n\tpsSubCodeMethod cannot be resolved\n\tStringHelper cannot be resolved\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tiPSAppView cannot be resolved or is not a field\n\tiPSAppView cannot be resolved or is not a field\n\tiPSAppView cannot be resolved to a variable\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n\tIPSAppView cannot be resolved to a type\n");
    }
}

