#LDAPServer

ldap.url=ldap://localhost:389
ldap.user=cn=Manager,dc=ibizsys,dc=net
ldap.pass=ldaptest

server.initconn=true
server.user=root
server.pass=ldaptest
server.ip=localhost
server.port=22
server.ldapprofile=/var/lib/ldap/cfg/
