%DEDQ_FIELDCOND%=\
    <#if cond.getPSVARTypeId()?? && (cond.getPSVARTypeId()?length gt 0)> \
      <#if cond.isIgnoreEmpty()> \
      <#noparse><choose><when test="ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse> !=null "></#noparse> \
      </#if> \
        ${field} \
        <#if cond.getPSDBValueOPId() == 'EQ' >\
        <#noparse>=</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'ABSEQ' >\
        <#noparse>=</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'GT' >\
        <#noparse>></#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'GTANDEQ' >\
        <#noparse>>=</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'LT' >\
        <#noparse><</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'LTANDEQ' >\
        <#noparse><=</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'NOTEQ' >\
        <#noparse><></#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'ISNULL' >\
        <#noparse>IS NULL</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'ISNOTNULL' >\
        <#noparse>IS NOT NULL</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'USERLIKE' >\
        <#noparse>LIKE</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'LIKE' >\
        <#noparse>LIKE</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'LEFTLIKE' >\
        <#noparse>LIKE</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'RIGHTLIKE' >\
        <#noparse>LIKE</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'TESTNULL' >\
        # <#noparse>!=</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'IN' >\
        <#noparse>IN</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'NOTIN' >\
        <#noparse>NOT IN</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'CHILDOF' >\
        # <#noparse>!=</#noparse> \
        <#elseif cond.getPSDBValueOPId() == 'PARENTOF' >\
        # <#noparse>!=</#noparse> \
        </#if>\
        <#if cond.getCondValue()?? && (cond.getCondValue()?length gt 0)>\
            <#if cond.getPSDBValueOPId() == 'LIKE'>\
                <#if dbtype == 'MYSQL5'>\
                <#noparse>CONCAT('%',#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>},'%')</#noparse> \
                <#elseif dbtype == 'ORACLE'>\
                <#noparse>'%' || #{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>} || '%'</#noparse> \
                <#else>\
                <#noparse>#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>}</#noparse> \
                </#if>\
            <#elseif cond.getPSDBValueOPId() == 'USERLIKE'>\
                <#if dbtype == 'MYSQL5'>\
                <#noparse>CONCAT('%',#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>},'%')</#noparse> \
                <#elseif dbtype == 'ORACLE'>\
                <#noparse>'%' || #{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>} || '%'</#noparse> \
                <#else>\
                <#noparse>#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>}</#noparse> \
                </#if>\
            <#elseif cond.getPSDBValueOPId() == 'LEFTLIKE' >\
                <#if dbtype == 'MYSQL5'>\
                <#noparse>CONCAT('%',#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>})</#noparse> \
                <#elseif dbtype == 'ORACLE'>\
                <#noparse>'%' || #{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>}</#noparse> \
                <#else>\
                <#noparse>#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>}</#noparse> \
                </#if>\
            <#elseif cond.getPSDBValueOPId() == 'RIGHTLIKE' >\
                <#if dbtype == 'MYSQL5'>\
                <#noparse>CONCAT(#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>},'%')</#noparse> \
                <#elseif dbtype == 'ORACLE'>\
                <#noparse>#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>} || '%'</#noparse> \
                <#else>\
                <#noparse>#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>}</#noparse> \
                </#if>\
            <#elseif cond.getPSDBValueOPId() == 'IN' >\
                <#noparse>({ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>})</#noparse> \
            <#else>\
            <#noparse>#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.${cond.getCondValue()?lower_case}<#noparse>}</#noparse> \
            </#if>\
        <#else>\
        <#noparse>#{ctx.</#noparse>${cond.getPSVARTypeId()?lower_case}.unknown<#noparse>}</#noparse> \
        </#if>\
        <#if cond.isIgnoreEmpty()> \
        <#noparse></when><otherwise>1=1</otherwise></choose></#noparse> \
        </#if> \
    <#else>\
        ${code}\
    </#if>