/*
 * Decompiled with CFR 0.152.
 */
package SA.SRFDA.Localization;

public class SRFDALanguageRes {
    public static final String ERROR_STD_DB_NOTALLOWEMPTY = "ERROR.STD.DB.NOTALLOWEMPTY";
    public static final String ERROR_STD_DB_DUPLICATEDATA = "ERROR.STD.DB.DUPLICATEDATA";
    public static final String ERROR_STD_DB_DUPLICATEDATA2 = "ERROR.STD.DB.DUPLICATEDATA2";
    public static final String ERROR_STD_DB_INVALIDDATA = "ERROR.STD.DB.INVALIDDATA";
    public static final String ERROR_STD_SRFDA_CANNOTFINDDEHELPER = "ERROR.STD.SRFDA.CANNOTFINDDEHELPER";
    public static final String ERROR_STD_SRFDA_CANNOTFINDDEDATACTRL = "ERROR.STD.SRFDA.CANNOTFINDDEDATACTRL";
    public static final String ERROR_STD_SRFDA_CANNOTFINDINDEXDEF = "ERROR.STD.SRFDA.CANNOTFINDINDEXDEF";
    public static final String CTRL_FORMAH_UNSAVENEWDATA = "CTRL.FORMAH.UNSAVENEWDATA";
    public static final String CTRL_FORMAH_DATASAVEDSUCCESSFULLY = "CTRL.FORMAH.DATASAVEDSUCCESSFULLY";
    public static final String CTRL_FORMAH_DATASAVEFAILED = "CTRL.FORMAH.DATASAVEFAILED";
    public static final String CTRL_FORMAH_NOTSPECIFYKEY = "CTRL.FORMAH.NOTSPECIFYKEY";
    public static final String CTRL_FORMAH_INPUTERROR = "CTRL.FORMAH.INPUTERROR";
    public static final String CTRL_FORMAH_INPUTERROR2 = "CTRL.FORMAH.INPUTERROR2";
    public static final String CTRL_FORMAH_DATAKEYERROR = "CTRL.FORMAH.DATAKEYERROR";
    public static final String CTRL_FORMAH_DATAALREADYREMOVED = "CTRL.FORMAH.DATAALREADYREMOVED";
}

